controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    position_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    diff_drive_controller:  
      type: "diff_drive_controller/DiffDriveController"

diff_drive_controller:
  ros__parameters:    
      left_wheel  : "left_wheel_joint"
      right_wheel : "right_wheel_joint"
      publish_rate: 20.0               # default: 50   
      pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
      twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]

      # Wheel separation and diameter. These are both optional.
      # diff_drive_controller will attempt to read either one or both from the
      # URDF if not specified as a parameter
      wheel_separation : 0.11
      wheel_radius : 0.0325

      # Wheel separation and radius multipliers
      wheel_separation_multiplier: 1.0 # default: 1.0
      wheel_radius_multiplier    : 1.0 # default: 1.0

      # Velocity commands timeout [s], default 0.5
      cmd_vel_timeout: 0.25       

      # Base frame_id
      base_frame_id: "base_footprint"
      odom_frame_id: "/odom"    

    # Publish the velocity command to be executed.
    # It is to monitor the effect of limiters on the controller input.
      publish_cmd: true
      enable_odom_tf: true  

forward_position_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
    interface_name: position


position_trajectory_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2

    command_interfaces:
      - position

    state_interfaces:
      - position

    state_publish_rate: 200.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)
